### ISSUE TITLE
Automatic install not working

### ISSUE THREAD

**Issue by AminGtt** [i-doit/scripts#24]
### Expected behavior

Automatic install and no problems

### Actual behavior

I am just following the steps in the guide, everything is OK until the "tenant" step, the script ask me if I want to automatically create the initial tenant and when I say yes I got a PHP fatal error so I am locked, I tried to do it manually and I realized that there is only two tabs in the top menu bar (addons and config) instead of more. I cannot create any tenant and finish my setup. Please help me :)

### Steps to reproduce the behavior

Follow the steps of the automatic install

### Environment

| Question                  | Answer                            |
| ------------------------- | --------------------------------- |
| i-doit version            | 1.18                             |
| i-doit edition            |  open                   |
| Operating system (OS)     | Debian  |
| OS version                | 11 "bullseye"                       |

### Server logs

Do you want to create the initial i-doit tenant automatically? [Y]es [n]o: 
Install i-doit via console.php
Please enter a tenant name [leave empty for 'Your company name']: 
PHP Fatal error:  Uncaught Error: Class 'idoit\Module\License\LicenseServiceFactory' not found in /var/www/html/src/classes/modules/console/src/Console/Command/Tenant/AddTenantCommand.php:168
Stack trace:
#0 /var/www/html/src/classes/modules/console/src/Console/Command/AbstractConfigurableCommand.php(137): idoit\Module\Console\Console\Command\Tenant\AddTenantCommand->createStep()
#1 /var/www/html/vendor/symfony/console/Command/Command.php(298): idoit\Module\Console\Console\Command\AbstractConfigurableCommand->execute()
#2 /var/www/html/vendor/symfony/console/Application.php(1023): Symfony\Component\Console\Command\Command->run()
#3 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /var/www/html/console.php(26): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in /var/www/html/src/classes/modules/console/src/Console/Command/Tenant/AddTenantCommand.php on line 168
Creating tenant failed
Operation failed. Please check what is wrong and try again.

**Comment by mindsolve** [comment]
Hi, I am encountering the same problem (same system, same steps). This also occurs if trying to add a tenant directly via the `idoit` CLI.

**Comment by MichaelOv** [comment]
Hey @AminGtt, 
it looks like we need to take out the installation for the open version. I will clarify that. 
If you are stuck on this step delete the File `src/config.inc.php` and do the installation via the GUI.

**Comment by MichaelOv** [comment]
---Update---
It seems to be a Bug in the i-doit code.
The Dev's have to fix it there. So there is a internal Bug Report for it

**Comment by MichaelOv** [comment]
The Bug has been fixed the actual Package

**Comment by phoerselmann** [comment]
Close the issue as the bug is fixed in i-doit
