### ISSUE TITLE
i-doit.com certificate expiration causes automated deployment to fail

### ISSUE THREAD

**Issue by aptdamia** [i-doit/scripts#27]
### Expected behavior

The automatic script runs without issue.

### Actual behavior

```
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /tmp/i-doit_2022-05-22/parseupdates.php:3
Stack trace:
#0 /tmp/i-doit_2022-05-22/parseupdates.php(3): SimpleXMLElement->__construct('')
#1 {main}
  thrown in /tmp/i-doit_2022-05-22/parseupdates.php on line 3
```

### Steps to reproduce the behavior

Run the automated script with all options and PRO version.

### Environment

| Question                  | Answer                            |
| ------------------------- | --------------------------------- |
| i-doit version            | 1.18                             |
| i-doit edition            | pro                   |
| Operating system (OS)     | Debian  |
| OS version                | 10                       |

### Cause

```
Identify latest version of i-doit pro
--2022-05-22 16:27:57--  https://i-doit.com/updates.xml
Resolving i-doit.com (i-doit.com)... 35.242.168.23
Connecting to i-doit.com (i-doit.com)|35.242.168.23|:443... connected.
ERROR: The certificate of ‘i-doit.com’ is not trusted.
ERROR: The certificate of ‘i-doit.com’ has expired.
The certificate has expired
```

It looks like the certificate for i-doi.com has expired. By using the `--no-check-certificate` option, the script run without issue.

**Comment by aptdamia** [comment]
The line causing the issue is 1728:
"$WGET_BIN" --quiet -O "${TMP_DIR}/updates.xml" "$update_file_url"

My substitution to make it "work" is:
"$WGET_BIN" --no-check-certificate -O "${TMP_DIR}/updates.xml" "$update_file_url"

**Comment by phoerselmann** [comment]
Hello @aptdamia thank you for the hint. We are working in the certifcate issue to fix this as fast as possible

**Comment by phoerselmann** [comment]
Hello @aptdamia  the certificate issue is solved
As the certificate check should remain here, I will close the issue.
Thanks again
