### ISSUE TITLE
Update required for installation script

### ISSUE THREAD

**Issue by Vip3rLi0n** [i-doit/scripts#28]
Please update installation script to work for Ubuntu 22.04

**Comment by MichaelOv** [comment]
Hey @Ni3zam ubuntu 22.04 is not supported because php 8.0 is not shipped with it, as soon as i-doit supports php 8.1/8.2 we will adapt the script.

**Comment by andreas-noethen** [comment]
https://github.com/i-doit/scripts/blob/main/idoit-install#L1164  ff

install_script does not allow ANY php version besides 7.3 and 7.4
...which are both beyond end od life

**Comment by MichaelOv** [comment]
Ubuntu 22.04 is supported
