### ISSUE TITLE
idoit-install fails on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by muttersda** [i-doit/scripts#41]
### Expected behavior

The installer completes successfully.

### Actual behavior

The installer fails at multiple points.  At issue are the OS version, PHP version, and MariaDB version.

### Steps to reproduce the behavior

Attempt to run idoit-install on Ubuntu 24.04 LTS.

### Environment

| Question                  | Answer                            |
| ------------------------- | --------------------------------- |
| i-doit version            | 30 (script pulled from main on 5-9-24)                             |
| i-doit edition            | open                   |
| Operating system (OS)     | Ubuntu   |
| OS version                | 24.04                       |

### Server logs

(MariaDB|Ubuntu|PHP) <version> is not supported.

### Suggested Solution
I've made the necessary changes to idoit-install and attached a diff file, below.

`patch idoit-install idoit-install_diff.txt`

**Comment by muttersda** [comment]
[idoit-install_diff.txt](https://github.com/i-doit/scripts/files/15265297/idoit-install_diff.txt)

**Comment by muttersda** [comment]
The Apache2 configuration at /etc/apache2/sites-available/i-doit.conf also needs to be altered to account for PHP version 8.3.  Diff attached.
[i-doit.conf_diff.txt](https://github.com/i-doit/scripts/files/15265534/i-doit.conf_diff.txt)

**Comment by MichaelOv** [comment]
Hey @muttersda again,

i will add it but we will still abort if using Ubuntu 24.04 because it uses PHP 8.3 which is not yet support by i-doit
